version: '3.8'

services:
  app:
    build: .
    ports:
      - "6969:6969"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/recipes
      SPRING_DATASOURCE_USERNAME: recipesUser
      SPRING_DATASOURCE_PASSWORD: recipesPassword
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: recipesUser
      POSTGRES_PASSWORD: recipesPassword
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: